"""Crear tablas de sesiones y mensajes

Revision ID: e58b41a2be8c
Revises: 6409ac680ebd
Create Date: 2026-05-18 00:08:28.497139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e58b41a2be8c'
down_revision: Union[str, Sequence[str], None] = '6409ac680ebd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sesiones_chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sesiones_chat_id'), 'sesiones_chat', ['id'], unique=False)
    op.create_table('mensajes_chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sesion_id', sa.Integer(), nullable=False),
    sa.Column('remitente', sa.String(), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sesion_id'], ['sesiones_chat.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mensajes_chat_id'), 'mensajes_chat', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mensajes_chat_id'), table_name='mensajes_chat')
    op.drop_table('mensajes_chat')
    op.drop_index(op.f('ix_sesiones_chat_id'), table_name='sesiones_chat')
    op.drop_table('sesiones_chat')
    # ### end Alembic commands ###
